import Image from 'next/image'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="container">
        <p> Disclaimer: <br />

Welcome to Falcon Chat APP! Before using our chatbot or relying on any information provided by it, we kindly request that you carefully read and understand the following disclaimer. By accessing or using our chatbot, you acknowledge that you have read, understood, and agreed to be bound by this disclaimer. <br />
<br />
<em>General Purpose and Information Accuracy:</em><br />
Our chatbot is designed to provide general information and assist you in gaining a better understanding of funds regulation and related topics. However, it is important to note that the responses generated by the chatbot are based on artificial intelligence and machine learning algorithms. While we strive to provide accurate and up-to-date information, we cannot guarantee the accuracy, completeness, or timeliness of the responses.<br />
<br />
<em>No Legal Advice Provided:</em><br />
The information and responses provided by our chatbot are not intended to constitute legal advice. They should not be considered as a substitute for professional legal advice or consultation. Our chatbot's purpose is to provide general information and educational content only. It is strongly recommended that you consult with a qualified legal professional or seek expert advice to verify the accuracy and applicability of any information obtained through the chatbot.<br />
<br />
<em>Consult a Lawyer:</em><br />
Given the limitations of artificial intelligence and the complexities of legal matters, we strongly advise consulting a licensed attorney or legal expert for any specific legal concerns or questions you may have. Legal matters can be highly nuanced and can vary based on specific jurisdictions, regulations, and circumstances. Only a qualified legal professional can provide you with personalized advice tailored to your unique situation.<br />
<br />
<em>No Legal Relationship Created:</em><br />
Your use of the chatbot and any interaction with it does not create an attorney-client relationship or any other professional relationship between you and [Your Company Name]. No confidential or privileged information should be shared with the chatbot. We do not accept any responsibility for any consequences or damages arising from the use or reliance on the chatbot or any information provided by it.<br />
<br />
<em>Limitation of Liability:</em><br />
Falcon, its affiliates, employees, agents, and partners shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with the use of the chatbot or reliance on its information. You agree to use the chatbot at your own risk.<br />
<br />
<em>Third-Party Links and Content:</em><br />
Our chatbot may contain links to third-party websites or content. These links are provided for convenience and informational purposes only. [Your Company Name] does not endorse or assume any responsibility for the accuracy, legality, or appropriateness of the content on such websites. Accessing and using third-party links and content are at your own discretion and risk.<br />
<br />
<em>Changes to Disclaimer:</em><br />
We reserve the right to modify, update, or remove any part of this disclaimer at any time without prior notice. It is your responsibility to review the disclaimer periodically for any changes. Continued use of our chatbot after any modifications to the disclaimer constitutes your acceptance of the revised terms.<br />
<br />
<br />
By using our chatbot, you agree to the terms and conditions outlined in this disclaimer. If you do not agree with any part of this disclaimer, please refrain from using our chatbot.<br />

If you have any questions or concerns regarding this disclaimer, please contact us at [Contact Email Address].</p>
      </div>
      <div className="btn-container">
      <button class="accept-agreement" type="submit">ACCEPT</button>
      <button class="cancel-agreement" type="submit">CANCEL</button>
      </div>

    </main>
    
  )
}
